logging:
  level: INFO
  loggers:
    sockkeeper: INFO

server:
  applicationConnectors:
    - type: http
      port: 7777
  adminConnectors:
    - type: http
      port: 7778

redisConfig:
  hostname: localhost
  port: 6379