logging:
  level: INFO
  loggers:
    sockkeeper: INFO

server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889

redisConfig:
  hostname: localhost
  port: 6379